services:
  user-service-mysql:
    image: mysql:8.0
    container_name: user-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql/user-service-mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  user-service-was:
    build:
      context: ./user-service
    container_name: user-service-was
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-service-mysql:3306/user
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "7081:8080"
    depends_on:
      - user-service-mysql
    networks:
      - app-network

  product-service-mysql:
    image: mysql:8.0
    container_name: product-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql/product-service-mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - app-network

  product-service-was:
    build:
      context: ./product-service

    container_name: product-service-was
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://product-service-mysql:3306/user
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "7082:8080"
    depends_on:
      - product-service-mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge