services:
  user-service-mysql:
    image: mysql:8.0
    container_name: user-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql/user-service-mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  user-service-was:
    build:
      context: ./user-service
    container_name: user-service-was
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-service-mysql:3306/user
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
        - user-service-mysql
    networks:
        - app-network



networks:
  app-network:
    driver: bridge